services:
  redis:
    image: redis:7-alpine
    container_name: aroha-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  price-server:
    build: .
    container_name: aroha-price-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=4000
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "4000:4000"

volumes:
  redis_data:
