version: "3.9"

services:
  # ===========================
  # KeyDB (Redis-compatible)
  # ===========================
  keydb:
    image: eqalpha/keydb:latest
    container_name: aroha-keydb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    command: keydb-server --appendonly yes --save "60 1"
    networks:
      - aroha-net

  # ===========================
  # Price Server
  # ===========================
  price-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-price-server
    restart: unless-stopped
    working_dir: /app/backend/price-server
    env_file:
      - ./backend/price-server/.env
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URL=redis://keydb:6379
    depends_on:
      - keydb
    ports:
      - "4000:4000"
    command: ["node", "index.js"]
    networks:
      - aroha-net

  # ===========================
  # Matching Engine
  # ===========================
  matching-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-matching-engine
    restart: unless-stopped
    working_dir: /app/backend/matching-engine
    env_file:
      - ./backend/matching-engine/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://keydb:6379
    depends_on:
      - keydb
      - price-server
    command: ["node", "matchingEngine.js"]
    networks:
      - aroha-net

volumes:
  keydb_data:

networks:
  aroha-net:
    driver: bridge
