version: "3.9"

services:
  # ===========================
  # KeyDB (Redis-compatible)
  # ===========================
  aroha-keydb:
    image: eqalpha/keydb:latest
    container_name: aroha-keydb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    command: keydb-server --appendonly yes --save "60 1"
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===========================
  # Publisher (Binance → Redis)
  # ===========================
  aroha-publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-publisher
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379
      - VERBOSE_LOGS=false
    depends_on:
      aroha-keydb:
        condition: service_healthy
    command: ["pm2-runtime", "backend/price-server/publisher.js"]
    networks:
      - aroha-net
    healthcheck:
      disable: true

  # ===========================
  # Price Server (WS + REST API)
  # ===========================
  aroha-price-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-price-server
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379
    depends_on:
      aroha-keydb:
        condition: service_healthy
      aroha-publisher:
        condition: service_started
    ports:
      - "4000:4000"
    command: ["pm2-runtime", "backend/price-server/index.js"]
    networks:
      - aroha-net
    healthcheck:
      disable: true

  # ===========================
  # Matching Engine
  # ===========================
  aroha-matching-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-matching-engine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379
    depends_on:
      aroha-keydb:
        condition: service_healthy
      aroha-publisher:
        condition: service_started
      aroha-price-server:
        condition: service_started
    command: ["pm2-runtime", "backend/matching-engine/matchingEngine.js"]
    networks:
      - aroha-net
    healthcheck:
      disable: true

volumes:
  keydb_data:

networks:
  aroha-net:
    driver: bridge
