version: "3.9"

services:
  # ===========================
  # KeyDB (Redis-compatible)
  # ===========================
  keydb:
    image: eqalpha/keydb:latest
    container_name: aroha-keydb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    command: keydb-server --appendonly yes --save "60 1"
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Publisher (Binance Feed → Redis)
  # ===========================
  aroha-publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-publisher
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      keydb:
        condition: service_healthy
    command: ["node", "/app/backend/price-server/publisher.js"]
    networks:
      - aroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Price Server (WS + REST API)
  # ===========================
  aroha-price-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-price-server
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      keydb:
        condition: service_healthy
      aroha-publisher:
        condition: service_started
    ports:
      - "4000:4000"
    command: ["pm2-runtime", "/app/backend/price-server/index.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/metrics"]
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Matching Engine
  # ===========================
  aroha-matching-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-matching-engine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      aroha-price-server:
        condition: service_started
    command: ["pm2-runtime", "/app/backend/matching-engine/matchingEngine.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "aroha-keydb", "ping"]   # 🔥 fixed
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Risk Engine
  # ===========================
  aroha-risk-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-risk-engine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      aroha-matching-engine:
        condition: service_started
    command: ["pm2-runtime", "/app/backend/price-server/riskEngine.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "aroha-keydb", "ping"]   # 🔥 fixed
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Candle Worker (OHLC)
  # ===========================
  aroha-candle-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-candle-worker
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      aroha-price-server:
        condition: service_started
    command: ["pm2-runtime", "/app/backend/price-server/candleWorker.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "aroha-keydb", "ping"]   # 🔥 fixed
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Relay Server (Frontend WS)
  # ===========================
  aroha-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-relay
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - RELAY_PORT=8080
      - REDIS_URL=redis://aroha-keydb:6379   # 🔥 fixed
    depends_on:
      keydb:
        condition: service_healthy
    command: ["node", "/app/relay.js"]
    ports:
      - "8080:8080"
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Redis Exporter (KeyDB Metrics)
  # ===========================
  aroha-redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: aroha-redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://aroha-keydb:6379   # 🔥 fixed
    ports:
      - "9121:9121"
    networks:
      - aroha-net
    depends_on:
      - keydb
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Node Exporter (Host Metrics)
  # ===========================
  aroha-node-exporter:
    image: prom/node-exporter:latest
    container_name: aroha-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - aroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Prometheus (Metrics DB)
  # ===========================
  aroha-prometheus:
    image: prom/prometheus:latest
    container_name: aroha-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - aroha-net
    depends_on:
      - aroha-redis-exporter
      - aroha-node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Alertmanager (Notifications)
  # ===========================
  aroha-alertmanager:
    image: prom/alertmanager:latest
    container_name: aroha-alertmanager
    restart: unless-stopped
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - aroha-net
    depends_on:
      - aroha-prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Grafana (Dashboard UI)
  # ===========================
  aroha-grafana:
    image: grafana/grafana:latest
    container_name: aroha-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - aroha-prometheus
      - aroha-alertmanager
    networks:
      - aroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # ===========================
  # Nginx Reverse Proxy (SSL + API Gateway)
  # ===========================
  aroha-nginx:
    image: nginx:latest
    container_name: aroha-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - aroha-price-server
      - aroha-relay
      - aroha-grafana
      - aroha-prometheus
    networks:
      - aroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  keydb_data:
  prometheus_data:
  grafana_data:

networks:
  aroha-net:
    driver: bridge
