services:
  # ===========================
  # KeyDB (Redis-compatible)
  # ===========================
  keydb:
    image: eqalpha/keydb:latest
    container_name: aroha-keydb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    command: keydb-server --appendonly yes --save "60 1"
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===========================
  # Publisher (Binance → Redis)
  # ===========================
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-publisher
    restart: unless-stopped
    working_dir: /app/backend/price-server
    env_file:
      - ./backend/price-server/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://keydb:6379
    depends_on:
      keydb:
        condition: service_healthy
    command: ["pm2-runtime", "publisher.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('./publisher.js')\" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  # ===========================
  # Price Server (WS + REST API)
  # ===========================
  price-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-price-server
    restart: unless-stopped
    working_dir: /app/backend/price-server
    env_file:
      - ./backend/price-server/.env
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URL=redis://keydb:6379
    depends_on:
      keydb:
        condition: service_healthy
      publisher:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: ["pm2-runtime", "index.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/prices || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  # ===========================
  # Matching Engine
  # ===========================
  matching-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroha-matching-engine
    restart: unless-stopped
    working_dir: /app/backend/matching-engine
    env_file:
      - ./backend/matching-engine/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://keydb:6379
    depends_on:
      keydb:
        condition: service_healthy
      publisher:
        condition: service_healthy
      price-server:
        condition: service_healthy
    command: ["pm2-runtime", "matchingEngine.js"]
    networks:
      - aroha-net
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('./matchingEngine.js')\" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  keydb_data:

networks:
  aroha-net:
    driver: bridge
